queue:
  name: Default
steps:
- task: ArchiveFiles@1
  inputs:
    rootFolder: "source"
    includeRootFolder: "false"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
    ArtifactName: "SourceArtifact"
    ArtifactType: "Container"
